function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the DSP System Toolbox 9.2.
% Generated on: 13-May-2016 18:45:18

persistent Hd;

if isempty(Hd)
    
    N     = 20;    % Order
    Fstop = 0.7;  % Stopband Frequency
    Astop = 80;    % Stopband Attenuation (dB)
    Apass = 1;     % Passband Ripple (dB)
    Fs    = 100;   % Sampling Frequency
    
    h = fdesign.highpass('n,fst,ast,ap', N, Fstop, Astop, Apass, Fs);
    
    Hd = design(h, 'equiripple', ...
        'StopbandShape', 'flat');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

